/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalProjectIdRouteImport } from './routes/portal/$projectId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as PortalProjectIdSettingsRouteImport } from './routes/portal/$projectId/settings'
import { Route as PortalProjectIdMyFeedbackRouteImport } from './routes/portal/$projectId/my-feedback'
import { Route as PortalProjectIdFeaturesRouteImport } from './routes/portal/$projectId/features'
import { Route as AuthAcceptInviteTokenRouteImport } from './routes/auth/accept-invite.$token'
import { Route as AuthenticatedProjectsProjectIdConsoleIndexRouteImport } from './routes/_authenticated/projects/$projectId/console/index'
import { Route as AuthenticatedProjectsProjectIdCommunityIndexRouteImport } from './routes/_authenticated/projects/$projectId/community/index'
import { Route as AuthenticatedProjectsProjectIdConsoleSettingsRouteImport } from './routes/_authenticated/projects/$projectId/console/settings'
import { Route as AuthenticatedProjectsProjectIdConsoleSdkTokensRouteImport } from './routes/_authenticated/projects/$projectId/console/sdk-tokens'
import { Route as AuthenticatedProjectsProjectIdConsoleMembersRouteImport } from './routes/_authenticated/projects/$projectId/console/members'
import { Route as AuthenticatedProjectsProjectIdCommunityFeatureIdRouteImport } from './routes/_authenticated/projects/$projectId/community/$featureId'
import { Route as AuthenticatedProjectsProjectIdConsoleUsersIndexRouteImport } from './routes/_authenticated/projects/$projectId/console/users/index'
import { Route as AuthenticatedProjectsProjectIdConsoleUsersUserIdRouteImport } from './routes/_authenticated/projects/$projectId/console/users/$userId'
import { Route as AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRouteImport } from './routes/_authenticated/projects/$projectId/console/feedback.$feedbackId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProjectIdRoute = PortalProjectIdRouteImport.update({
  id: '/portal/$projectId',
  path: '/portal/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PortalProjectIdSettingsRoute = PortalProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalProjectIdRoute,
} as any)
const PortalProjectIdMyFeedbackRoute =
  PortalProjectIdMyFeedbackRouteImport.update({
    id: '/my-feedback',
    path: '/my-feedback',
    getParentRoute: () => PortalProjectIdRoute,
  } as any)
const PortalProjectIdFeaturesRoute = PortalProjectIdFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => PortalProjectIdRoute,
} as any)
const AuthAcceptInviteTokenRoute = AuthAcceptInviteTokenRouteImport.update({
  id: '/auth/accept-invite/$token',
  path: '/auth/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsProjectIdConsoleIndexRoute =
  AuthenticatedProjectsProjectIdConsoleIndexRouteImport.update({
    id: '/projects/$projectId/console/',
    path: '/projects/$projectId/console/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdCommunityIndexRoute =
  AuthenticatedProjectsProjectIdCommunityIndexRouteImport.update({
    id: '/projects/$projectId/community/',
    path: '/projects/$projectId/community/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdConsoleSettingsRoute =
  AuthenticatedProjectsProjectIdConsoleSettingsRouteImport.update({
    id: '/projects/$projectId/console/settings',
    path: '/projects/$projectId/console/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdConsoleSdkTokensRoute =
  AuthenticatedProjectsProjectIdConsoleSdkTokensRouteImport.update({
    id: '/projects/$projectId/console/sdk-tokens',
    path: '/projects/$projectId/console/sdk-tokens',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdConsoleMembersRoute =
  AuthenticatedProjectsProjectIdConsoleMembersRouteImport.update({
    id: '/projects/$projectId/console/members',
    path: '/projects/$projectId/console/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdCommunityFeatureIdRoute =
  AuthenticatedProjectsProjectIdCommunityFeatureIdRouteImport.update({
    id: '/projects/$projectId/community/$featureId',
    path: '/projects/$projectId/community/$featureId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdConsoleUsersIndexRoute =
  AuthenticatedProjectsProjectIdConsoleUsersIndexRouteImport.update({
    id: '/projects/$projectId/console/users/',
    path: '/projects/$projectId/console/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdConsoleUsersUserIdRoute =
  AuthenticatedProjectsProjectIdConsoleUsersUserIdRouteImport.update({
    id: '/projects/$projectId/console/users/$userId',
    path: '/projects/$projectId/console/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRoute =
  AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRouteImport.update({
    id: '/projects/$projectId/console/feedback/$feedbackId',
    path: '/projects/$projectId/console/feedback/$feedbackId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/portal/$projectId': typeof PortalProjectIdRouteWithChildren
  '/auth/accept-invite/$token': typeof AuthAcceptInviteTokenRoute
  '/portal/$projectId/features': typeof PortalProjectIdFeaturesRoute
  '/portal/$projectId/my-feedback': typeof PortalProjectIdMyFeedbackRoute
  '/portal/$projectId/settings': typeof PortalProjectIdSettingsRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/community/$featureId': typeof AuthenticatedProjectsProjectIdCommunityFeatureIdRoute
  '/projects/$projectId/console/members': typeof AuthenticatedProjectsProjectIdConsoleMembersRoute
  '/projects/$projectId/console/sdk-tokens': typeof AuthenticatedProjectsProjectIdConsoleSdkTokensRoute
  '/projects/$projectId/console/settings': typeof AuthenticatedProjectsProjectIdConsoleSettingsRoute
  '/projects/$projectId/community': typeof AuthenticatedProjectsProjectIdCommunityIndexRoute
  '/projects/$projectId/console': typeof AuthenticatedProjectsProjectIdConsoleIndexRoute
  '/projects/$projectId/console/feedback/$feedbackId': typeof AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRoute
  '/projects/$projectId/console/users/$userId': typeof AuthenticatedProjectsProjectIdConsoleUsersUserIdRoute
  '/projects/$projectId/console/users': typeof AuthenticatedProjectsProjectIdConsoleUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/portal/$projectId': typeof PortalProjectIdRouteWithChildren
  '/auth/accept-invite/$token': typeof AuthAcceptInviteTokenRoute
  '/portal/$projectId/features': typeof PortalProjectIdFeaturesRoute
  '/portal/$projectId/my-feedback': typeof PortalProjectIdMyFeedbackRoute
  '/portal/$projectId/settings': typeof PortalProjectIdSettingsRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/community/$featureId': typeof AuthenticatedProjectsProjectIdCommunityFeatureIdRoute
  '/projects/$projectId/console/members': typeof AuthenticatedProjectsProjectIdConsoleMembersRoute
  '/projects/$projectId/console/sdk-tokens': typeof AuthenticatedProjectsProjectIdConsoleSdkTokensRoute
  '/projects/$projectId/console/settings': typeof AuthenticatedProjectsProjectIdConsoleSettingsRoute
  '/projects/$projectId/community': typeof AuthenticatedProjectsProjectIdCommunityIndexRoute
  '/projects/$projectId/console': typeof AuthenticatedProjectsProjectIdConsoleIndexRoute
  '/projects/$projectId/console/feedback/$feedbackId': typeof AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRoute
  '/projects/$projectId/console/users/$userId': typeof AuthenticatedProjectsProjectIdConsoleUsersUserIdRoute
  '/projects/$projectId/console/users': typeof AuthenticatedProjectsProjectIdConsoleUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/portal/$projectId': typeof PortalProjectIdRouteWithChildren
  '/auth/accept-invite/$token': typeof AuthAcceptInviteTokenRoute
  '/portal/$projectId/features': typeof PortalProjectIdFeaturesRoute
  '/portal/$projectId/my-feedback': typeof PortalProjectIdMyFeedbackRoute
  '/portal/$projectId/settings': typeof PortalProjectIdSettingsRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/community/$featureId': typeof AuthenticatedProjectsProjectIdCommunityFeatureIdRoute
  '/_authenticated/projects/$projectId/console/members': typeof AuthenticatedProjectsProjectIdConsoleMembersRoute
  '/_authenticated/projects/$projectId/console/sdk-tokens': typeof AuthenticatedProjectsProjectIdConsoleSdkTokensRoute
  '/_authenticated/projects/$projectId/console/settings': typeof AuthenticatedProjectsProjectIdConsoleSettingsRoute
  '/_authenticated/projects/$projectId/community/': typeof AuthenticatedProjectsProjectIdCommunityIndexRoute
  '/_authenticated/projects/$projectId/console/': typeof AuthenticatedProjectsProjectIdConsoleIndexRoute
  '/_authenticated/projects/$projectId/console/feedback/$feedbackId': typeof AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRoute
  '/_authenticated/projects/$projectId/console/users/$userId': typeof AuthenticatedProjectsProjectIdConsoleUsersUserIdRoute
  '/_authenticated/projects/$projectId/console/users/': typeof AuthenticatedProjectsProjectIdConsoleUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/portal/$projectId'
    | '/auth/accept-invite/$token'
    | '/portal/$projectId/features'
    | '/portal/$projectId/my-feedback'
    | '/portal/$projectId/settings'
    | '/projects'
    | '/projects/$projectId/community/$featureId'
    | '/projects/$projectId/console/members'
    | '/projects/$projectId/console/sdk-tokens'
    | '/projects/$projectId/console/settings'
    | '/projects/$projectId/community'
    | '/projects/$projectId/console'
    | '/projects/$projectId/console/feedback/$feedbackId'
    | '/projects/$projectId/console/users/$userId'
    | '/projects/$projectId/console/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/portal/$projectId'
    | '/auth/accept-invite/$token'
    | '/portal/$projectId/features'
    | '/portal/$projectId/my-feedback'
    | '/portal/$projectId/settings'
    | '/projects'
    | '/projects/$projectId/community/$featureId'
    | '/projects/$projectId/console/members'
    | '/projects/$projectId/console/sdk-tokens'
    | '/projects/$projectId/console/settings'
    | '/projects/$projectId/community'
    | '/projects/$projectId/console'
    | '/projects/$projectId/console/feedback/$feedbackId'
    | '/projects/$projectId/console/users/$userId'
    | '/projects/$projectId/console/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/auth/signup'
    | '/portal/$projectId'
    | '/auth/accept-invite/$token'
    | '/portal/$projectId/features'
    | '/portal/$projectId/my-feedback'
    | '/portal/$projectId/settings'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/community/$featureId'
    | '/_authenticated/projects/$projectId/console/members'
    | '/_authenticated/projects/$projectId/console/sdk-tokens'
    | '/_authenticated/projects/$projectId/console/settings'
    | '/_authenticated/projects/$projectId/community/'
    | '/_authenticated/projects/$projectId/console/'
    | '/_authenticated/projects/$projectId/console/feedback/$feedbackId'
    | '/_authenticated/projects/$projectId/console/users/$userId'
    | '/_authenticated/projects/$projectId/console/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  PortalProjectIdRoute: typeof PortalProjectIdRouteWithChildren
  AuthAcceptInviteTokenRoute: typeof AuthAcceptInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$projectId': {
      id: '/portal/$projectId'
      path: '/portal/$projectId'
      fullPath: '/portal/$projectId'
      preLoaderRoute: typeof PortalProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/$projectId/settings': {
      id: '/portal/$projectId/settings'
      path: '/settings'
      fullPath: '/portal/$projectId/settings'
      preLoaderRoute: typeof PortalProjectIdSettingsRouteImport
      parentRoute: typeof PortalProjectIdRoute
    }
    '/portal/$projectId/my-feedback': {
      id: '/portal/$projectId/my-feedback'
      path: '/my-feedback'
      fullPath: '/portal/$projectId/my-feedback'
      preLoaderRoute: typeof PortalProjectIdMyFeedbackRouteImport
      parentRoute: typeof PortalProjectIdRoute
    }
    '/portal/$projectId/features': {
      id: '/portal/$projectId/features'
      path: '/features'
      fullPath: '/portal/$projectId/features'
      preLoaderRoute: typeof PortalProjectIdFeaturesRouteImport
      parentRoute: typeof PortalProjectIdRoute
    }
    '/auth/accept-invite/$token': {
      id: '/auth/accept-invite/$token'
      path: '/auth/accept-invite/$token'
      fullPath: '/auth/accept-invite/$token'
      preLoaderRoute: typeof AuthAcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId/console/': {
      id: '/_authenticated/projects/$projectId/console/'
      path: '/projects/$projectId/console'
      fullPath: '/projects/$projectId/console'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/community/': {
      id: '/_authenticated/projects/$projectId/community/'
      path: '/projects/$projectId/community'
      fullPath: '/projects/$projectId/community'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/console/settings': {
      id: '/_authenticated/projects/$projectId/console/settings'
      path: '/projects/$projectId/console/settings'
      fullPath: '/projects/$projectId/console/settings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConsoleSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/console/sdk-tokens': {
      id: '/_authenticated/projects/$projectId/console/sdk-tokens'
      path: '/projects/$projectId/console/sdk-tokens'
      fullPath: '/projects/$projectId/console/sdk-tokens'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConsoleSdkTokensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/console/members': {
      id: '/_authenticated/projects/$projectId/console/members'
      path: '/projects/$projectId/console/members'
      fullPath: '/projects/$projectId/console/members'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConsoleMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/community/$featureId': {
      id: '/_authenticated/projects/$projectId/community/$featureId'
      path: '/projects/$projectId/community/$featureId'
      fullPath: '/projects/$projectId/community/$featureId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCommunityFeatureIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/console/users/': {
      id: '/_authenticated/projects/$projectId/console/users/'
      path: '/projects/$projectId/console/users'
      fullPath: '/projects/$projectId/console/users'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConsoleUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/console/users/$userId': {
      id: '/_authenticated/projects/$projectId/console/users/$userId'
      path: '/projects/$projectId/console/users/$userId'
      fullPath: '/projects/$projectId/console/users/$userId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConsoleUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/console/feedback/$feedbackId': {
      id: '/_authenticated/projects/$projectId/console/feedback/$feedbackId'
      path: '/projects/$projectId/console/feedback/$feedbackId'
      fullPath: '/projects/$projectId/console/feedback/$feedbackId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsProjectIdCommunityFeatureIdRoute: typeof AuthenticatedProjectsProjectIdCommunityFeatureIdRoute
  AuthenticatedProjectsProjectIdConsoleMembersRoute: typeof AuthenticatedProjectsProjectIdConsoleMembersRoute
  AuthenticatedProjectsProjectIdConsoleSdkTokensRoute: typeof AuthenticatedProjectsProjectIdConsoleSdkTokensRoute
  AuthenticatedProjectsProjectIdConsoleSettingsRoute: typeof AuthenticatedProjectsProjectIdConsoleSettingsRoute
  AuthenticatedProjectsProjectIdCommunityIndexRoute: typeof AuthenticatedProjectsProjectIdCommunityIndexRoute
  AuthenticatedProjectsProjectIdConsoleIndexRoute: typeof AuthenticatedProjectsProjectIdConsoleIndexRoute
  AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRoute: typeof AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRoute
  AuthenticatedProjectsProjectIdConsoleUsersUserIdRoute: typeof AuthenticatedProjectsProjectIdConsoleUsersUserIdRoute
  AuthenticatedProjectsProjectIdConsoleUsersIndexRoute: typeof AuthenticatedProjectsProjectIdConsoleUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsProjectIdCommunityFeatureIdRoute:
    AuthenticatedProjectsProjectIdCommunityFeatureIdRoute,
  AuthenticatedProjectsProjectIdConsoleMembersRoute:
    AuthenticatedProjectsProjectIdConsoleMembersRoute,
  AuthenticatedProjectsProjectIdConsoleSdkTokensRoute:
    AuthenticatedProjectsProjectIdConsoleSdkTokensRoute,
  AuthenticatedProjectsProjectIdConsoleSettingsRoute:
    AuthenticatedProjectsProjectIdConsoleSettingsRoute,
  AuthenticatedProjectsProjectIdCommunityIndexRoute:
    AuthenticatedProjectsProjectIdCommunityIndexRoute,
  AuthenticatedProjectsProjectIdConsoleIndexRoute:
    AuthenticatedProjectsProjectIdConsoleIndexRoute,
  AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRoute:
    AuthenticatedProjectsProjectIdConsoleFeedbackFeedbackIdRoute,
  AuthenticatedProjectsProjectIdConsoleUsersUserIdRoute:
    AuthenticatedProjectsProjectIdConsoleUsersUserIdRoute,
  AuthenticatedProjectsProjectIdConsoleUsersIndexRoute:
    AuthenticatedProjectsProjectIdConsoleUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalProjectIdRouteChildren {
  PortalProjectIdFeaturesRoute: typeof PortalProjectIdFeaturesRoute
  PortalProjectIdMyFeedbackRoute: typeof PortalProjectIdMyFeedbackRoute
  PortalProjectIdSettingsRoute: typeof PortalProjectIdSettingsRoute
}

const PortalProjectIdRouteChildren: PortalProjectIdRouteChildren = {
  PortalProjectIdFeaturesRoute: PortalProjectIdFeaturesRoute,
  PortalProjectIdMyFeedbackRoute: PortalProjectIdMyFeedbackRoute,
  PortalProjectIdSettingsRoute: PortalProjectIdSettingsRoute,
}

const PortalProjectIdRouteWithChildren = PortalProjectIdRoute._addFileChildren(
  PortalProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  PortalProjectIdRoute: PortalProjectIdRouteWithChildren,
  AuthAcceptInviteTokenRoute: AuthAcceptInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
